# app/config/application.yml
  defaults: &defaults
    iim_app_id: 83u948$%@^po93kdERVsdfWRG932$%@jr3248jr2(K^!D39480^ry32HTEW984
    iim_domain: hub.iim.com.sg 
    nas_url: http://imagesinmotion.no-ip.biz/index.php
    nas_mp3_url: http://192.168.0.35/MP3/
    nas_zip_url: http://192.168.0.35/zip/
    
  development:
    <<: *defaults
    iim_domain: localhost:3000

  dev_work:
    <<: *defaults
    iim_domain: localhost:3000

  test:
    <<: *defaults

  production:
    <<: *defaults